# Generated by Django 6.0.1 on 2026-02-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixdesk_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='floor',
        ),
    ]
