# Generated by Django 6.0.1 on 2026-01-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixdesk_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='fixdesk_api.subscription'),
        ),
    ]
