# Generated by Django 6.0.1 on 2026-02-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixdesk_api', '0003_alter_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allowed_email_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
