# Generated by Django 6.0.1 on 2026-02-08 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixdesk_api', '0003_alter_verificationcode_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(db_index=True, default='staff', max_length=10)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accepted', models.BooleanField(db_index=True, default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='fixdesk_api.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
