# Generated by Django 6.0.1 on 2026-02-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityrequest',
            name='attachment_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issues',
            name='attachment_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='attachment_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facilityrequest',
            name='attachment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='attachment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='attachment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
